name: guard-immutable
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate IMMUTABLE regions
        run: |
          python3 .github/workflows/validate_immutable.py
