name: NinjaScript Lint

on:
  pull_request:
    paths:
      - "NT8Strategies/**"
      - "docs/ninjascript_contract.md"
      - "tools/ninjascript_lint.ps1"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Run NinjaScript Lint (PowerShell Core)
        shell: pwsh
        run: |
          ./tools/ninjascript_lint.ps1 -Path NT8Strategies
